docker-build:
  image: docker:cli
  stage: build
  services:
    - docker:dind
  variables:
    DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  before_script:
    - apk add --update --no-cache git
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        DOCKER_TAG="latest"
      else
        DOCKER_TAG="$CI_COMMIT_REF_SLUG"
      fi
    - docker buildx inspect --bootstrap || docker buildx create --use
    - docker buildx build --pull --platform linux/amd64,linux/arm64 -t "$CI_REGISTRY_IMAGE:$DOCKER_TAG" --push .
  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - Dockerfile
